### ISSUE TITLE
Repo deletion

### ISSUE THREAD

**Issue by JohnDoe42** [oliverguenther/openproject-revisions_git#17]
The git repo should not be deleted when the last member is removed from the project, but when the project itself is deleted. Otherwise it may happen, that the admin only wants to assign another team, removes everyone and adds the other team. In this case all work would be erased...

**Comment by JohnDoe42** [comment]
Even adding or removing a developer from a repository in use leads to a deletion and recreation of the repo.

**Comment by JohnDoe42** [comment]
Log:

```
update_repository : repository '<reponame>' already exists in Gitolite, removing first
Deleting obsolete repository /mnt/data2/gitolite/repositories/<reponame>
update_repository : commiting to Gitolite...
```

**Comment by oliverguenther** [comment]
Arh, yes. The original plugin removed the physical repo upon (re-)creating the repository in Gitolite if it existed before. This was due to purging any remaining files (e.g., if deletion of the old repository failed for some reason). The original plugin then used a different procedure to update repositories (i.e., member updates).

This forked plugin always overrides the configuration in gitolite by using a separate configuration, and thus we delete the repo configuration upon every update. As a remnant of the old plugin, the procedure also cleaned the physical repo, which is of course completely idiotic.
