### ISSUE TITLE
deployment keys are ignored

### ISSUE THREAD

**Issue by JohnDoe42** [oliverguenther/openproject-revisions_git#22]
Deployment keys are added to .ssh/authorized_keys but to none of the repos in openproject.conf - so the keys are currently useless.

At least the deployment keys should be added as read-only to all repos that the corresponding user has access to.

In the future the ability may be added to choose the repo, the deployment key belongs to.

**Comment by oliverguenther** [comment]
Yeah, deployment keys are still non-functional ([c.f., features](https://github.com/oliverguenther/openproject-revisions_git#features)) and we'll have to discuss what use-cases they should solve.

[The redmine plugin has the behavior](https://jbox-web.github.io/redmine_git_hosting/features/index.html#deployment-credentials) to add deployment keys on a per-repository level, while registering them on a per-user level (which is the remnant in this plugin you describe). So I agree, for fine-grained access control this is the path we should take, too.

**Comment by mabentwickeltsich** [comment]
Hi Oliver,

Any progress on the deployment keys?
I have been working on it and I have a functional feature. It still needs some fine tuning, but it is working. I was thinking in changing the directory structure of the public keys in the file system because for every key there is a new directory.

I am also working on repository mirrors and post receive urls. I do not know if you have some work on this area that is still not committed to the repository. Please, let me know to prevent double work on it.

And of course, I still need to work on OpenProject 5. I have been working with the version 4.2.

Cheers
Luis

**Comment by oliverguenther** [comment]
Hey Luis,

I have been working on providing an upgrade path to the managed repository API in OpenProject 5.0 (Kindly supported by the [ISP, Technische Universität Darmstadt](http://www.isp.informatik.tu-darmstadt.de/)).

As we're rolling out this plugin for them on 5.0.x, I'm going to provide maintenance to this plugin for this release.

That being said, due to my current involvement with OpenProject GmbH, free time to work on this plugin is limited. I accept and actively support pull requests. I do not have any work on that end, but will be able to help you in the migration of your code for 5.0.

Best,
Oliver

**Comment by mabentwickeltsich** [comment]
Hi Oliver,

I am not sure if I really understood what you said. Will OpenProject 5.0.x have the functionality provided by this plugin? I just do not want to spend time on this if next releases of OpenProject will have these features.

Kind regards
Luis

**Comment by oliverguenther** [comment]
Hey Luis,

Since this plugin was founded, I've joined OpenProject GmbH and, among many other things, have been working on [overhauling the entire repository management API](https://www.openproject.org/open-source/release-notes/openproject-5-0-0/enhanced-repository-management/) that was released with OpenProject 5.0 in November. It does not impact or include the functionality provided by this plugin, but simplifies the complexity of this plugin enormously, since the core is now open for new plugin SCM vendors (such as Gitolite).

Any work you make on a functional side will not be in vein for this plugin, but there may be some necessary alterations to the code that you wrote against dev (not directly release/5.0 compatible) compared to my 5.0-compatibility branch.

Does that make sense? Let me know if you need more information on this topic.
I highly appreciate your upcoming contribution!

Best,
Oliver

**Comment by mabentwickeltsich** [comment]
Hi Oliver,

Thanks for the feedback, that was very helpful.

Kind regards
Luis

**Comment by mabentwickeltsich** [comment]
This feature has been added and it is working.
